services:
  # 1. Aplikasi Next.js
  nextjs-app:
    build: .
    container_name: nextjs-app
    restart: always
    env_file:
      - .env
    # Kita tidak butuh 'depends_on' karena DB-nya di luar Docker
    networks:
      - app-network

  # 2. Web Server Nginx (Sebagai Pintu Masuk)
  nginx:
    build: ./nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - nextjs-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge